Yocto recipe for Kanto Local Digital Twins #5
eclipse-kanto/meta-kanto pull request #10
Opened 2022-08-11 09:42 UTC by hristobojilov

[#5] Yocto recipe for Kanto Local Digital Twins

Signed-off-by: Hristo Bozhilov <Hristo.Bozhilov@bosch.io>

2022-08-12 17:46 UTC, konstantina-gramatova approved these changes

2022-08-12 18:14 UTC, konstantina-gramatova requested changes

2022-08-12 18:14 UTC, konstantina-gramatova commented on recipes-connectivity/local-digital-twins/local-digital-twins.inc
> +# Common configuration variables to set the binaries and resources allocation directories for Eclipse Kanto Local digital twins component
Align the component's name (letters casing) and its usage in the recipe and all its resources.

2022-08-15 15:01 UTC, e-grigorov requested changes

2022-08-15 15:01 UTC, e-grigorov commented on recipes-connectivity/local-digital-twins/local-digital-twins_git.bb
> +
No need to use two empty lines.

2022-08-16 07:24 UTC, e-grigorov approved these changes

2022-08-16 07:27 UTC, e-grigorov requested changes

2022-08-16 07:27 UTC, e-grigorov commented on recipes-connectivity/local-digital-twins/local-digital-twins_git.bb
> +
We don't need two empty lines here, only one is enough.

2022-08-16 08:14 UTC, konstantina-gramatova approved these changes

2022-08-16 08:45 UTC, e-grigorov approved these changes

2022-08-16 08:49 UTC, merged