meta-kanto layer for Hardknott Yocto image
eclipse-kanto/meta-kanto pull request #109
Opened 2024-12-16 13:00 UTC by Mahesha-M

Described step by step instructions to include meta-kanto for hardknott yocto image.

2024-12-16 13:23 UTC, hristobojilov commented on README.md
> +    git ckecout <required_go_version_poky_branch>
Typo in the git command. Should be git checkout

2024-12-16 13:35 UTC, hristobojilov requested changes

2024-12-16 13:35 UTC, hristobojilov commented on README.md
> +3. Replace the Go version in your project build path "poky\meta\recipes-devtools" with
Add example what to replace exactly with what maybe be s some linux tools like sed or awk or patch

2024-12-16 13:35 UTC, hristobojilov commented on README.md
> +For further fine-tuning and options see the meta-virtualization README.
Add also link to this  meta-virtualization README file here

2024-12-16 13:35 UTC, hristobojilov commented on README.md
> +# Eclipse Kanto - Essential IoT enablement for edge devices
You have to fix github validation workflow for this branch https://github.com/eclipse-kanto/meta-kanto/blob/hardknott/.github/workflows/validation.yml

2024-12-17 11:26 UTC, Mahesha-M commented on README.md
> +For further fine-tuning and options see the meta-virtualization README.
Added the hardknott meta-virtualization README link.

2024-12-19 09:48 UTC, Mahesha-M commented on README.md
> +    git ckecout <required_go_version_poky_branch>
I've mentioned the examples for getting intended Go version from poky yocto branch

2024-12-19 09:49 UTC, Mahesha-M commented on README.md
> +3. Replace the Go version in your project build path "poky\meta\recipes-devtools" with
Added examples

2024-12-19 09:49 UTC, Mahesha-M commented on README.md
> +# Eclipse Kanto - Essential IoT enablement for edge devices
Fixed the validation script

2024-12-19 10:52 UTC, merged