Yocto recipe for Kanto Suite Bootstrapping #3
eclipse-kanto/meta-kanto pull request #11
Opened 2022-08-11 11:28 UTC by hristobojilov

[#3] Yocto recipe for Kanto Suite Bootstrapping

Signed-off-by: Hristo Bozhilov <Hristo.Bozhilov@bosch.io>

2022-08-12 18:04 UTC, konstantina-gramatova requested changes

2022-08-12 18:04 UTC, konstantina-gramatova commented on recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb
> +RPROVIDES:${PN} += "edge/suite-bootstrapping"
Must be prefixed with `kanto` not `edge`.

2022-08-15 14:00 UTC, e-grigorov requested changes

2022-08-15 14:00 UTC, e-grigorov commented on recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb
> +DESCRIPTION = "Eclipse Kanto - Suite Bootstrapping Agent"
Remove "Agent" from the description.

2022-08-15 14:00 UTC, e-grigorov commented on recipes-connectivity/suite-bootstrapping/files/service.template
> +
No need to have two empty lines. Only one should be enough.

2022-08-15 14:00 UTC, e-grigorov commented on recipes-connectivity/suite-bootstrapping/suite-bootstrapping.inc
> +# The destination directory where the required configuration files for the proper connectivity establishment of the bootstrapping agent will be placed
"bootstrapping agent" should be replaced by: suite bootstrapping

2022-08-15 14:00 UTC, e-grigorov commented on recipes-connectivity/suite-bootstrapping/suite-bootstrapping.inc
> +# The destination directory where the suite bootstrapping agent binaries will be placed
Remove "agent".

2022-08-15 14:00 UTC, e-grigorov commented on recipes-connectivity/suite-bootstrapping/suite-bootstrapping.inc
> +# The destination directory where the suite bootstrapping agent logs will be placed
Remove "agent".

2022-08-15 15:08 UTC, e-grigorov requested changes

2022-08-15 15:08 UTC, e-grigorov commented on recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb
> +
No need to use two empty lines.

2022-08-16 07:02 UTC, e-grigorov requested changes

2022-08-16 07:02 UTC, e-grigorov commented on recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb
> +   install -d ${D}${SB_SYSUNIT_DD}
The formatting is broken here, one space is missing.

2022-08-16 07:27 UTC, e-grigorov requested changes

2022-08-16 07:27 UTC, e-grigorov commented on recipes-connectivity/suite-bootstrapping/suite-bootstrapping_git.bb
> +
We don't need two empty lines here, only one is enough.

2022-08-16 08:11 UTC, konstantina-gramatova approved these changes

2022-08-16 08:48 UTC, e-grigorov approved these changes

2022-08-16 08:50 UTC, merged