Yocto recipe for Kanto Container Management #6
eclipse-kanto/meta-kanto pull request #27
Opened 2022-08-24 10:56 UTC by hristobojilov

[#6] Yocto recipe for Kanto Container Management

Signed-off-by: Hristo Bozhilov <Hristo.Bozhilov@bosch.io>

2022-08-24 11:43 UTC, e-grigorov commented
@hristobojilov The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-08-24 11:47 UTC, hristobojilov commented
> @hristobojilov The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances 😊
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

2022-08-24 15:35 UTC, e-grigorov requested changes

2022-08-24 15:35 UTC, e-grigorov commented on recipes-containers/container-management/container-management.inc
> +CM_SRV_REQ ?= "${@bb.utils.contains('PACKAGECONFIG', 'cloudconn', ' suite-connector.service', '',d)}"
cloudconn - what is it about?

2022-08-24 15:35 UTC, e-grigorov commented on recipes-containers/container-management/container-management_git.bb
> +PACKAGECONFIG[cloudconn] = "--with-cloudconn,--without-cloudconn,,kanto/suite-connector"
,, -> ,

2022-08-24 15:35 UTC, e-grigorov commented on recipes-containers/container-management/files/service.template
> +Requires=network.target containerd.service @CM_SRV_REQ@
There is no such dependency to the suite-connector for all other recipes. I am not sure that we need this one here. Even more, Azure connector can be used.

2022-08-24 15:35 UTC, e-grigorov commented on recipes-containers/container-management/container-management_git.bb
> +             ${GO_IMPORT}/containerm/cli \
The formatting can be fixed, see SRC_URI.

2022-08-31 07:26 UTC, konstantina-gramatova requested changes

2022-08-31 07:26 UTC, konstantina-gramatova commented on recipes-containers/container-management/container-management.inc
> +# The destination directory of the  containers management binaries
Please, align using containe**r** management everywhere.

2022-08-31 07:26 UTC, konstantina-gramatova commented on recipes-containers/container-management/container-management.inc
> +# Controls cloud connectivity for containers via suite connector
Enables the digital twin representation for container management

maybe? : )

2022-08-31 07:26 UTC, konstantina-gramatova commented on recipes-containers/container-management/container-management_git.bb
> +# standalone service.
Update accordingly based on the definition in the .in file - Enables the digital twin .....

as an integrated component of the suite connector  -> e.g. as an integrated Kanto component

2022-08-31 13:49 UTC, konstantina-gramatova requested changes

2022-08-31 13:49 UTC, konstantina-gramatova commented on recipes-containers/container-management/container-management.inc
> +# The destination directory of the  container management binaries
of the  container management -> fix the two spaces here

2022-08-31 13:49 UTC, konstantina-gramatova commented on recipes-containers/container-management/container-management.inc
> +# Enables the digital twin representation for container management
to finalize this description -> 

Enables the container management digital twin representation

2022-08-31 13:49 UTC, konstantina-gramatova commented on recipes-containers/container-management/container-management_git.bb
> +# This package feature enables the digital twin representation for container management.
Update accordingly to ->


This package feature enables the container management digital twin representation.

2022-08-31 14:27 UTC, konstantina-gramatova approved these changes

2022-08-31 15:12 UTC, konstantina-gramatova approved these changes

2022-09-01 07:23 UTC, e-grigorov approved these changes

2022-09-01 07:26 UTC, merged