Yocto recipe for Kanto File Backup #23
eclipse-kanto/meta-kanto pull request #28
Opened 2022-09-02 06:53 UTC by hristobojilov

[#23] Yocto recipe for Kanto File Backup
 
Signed-off-by: Hristo Bozhilov <Hristo.Bozhilov@bosch.io>

2022-09-08 07:06 UTC, konstantina-gramatova requested changes

2022-09-08 07:06 UTC, konstantina-gramatova commented on recipes-management/file-backup/files/config.json
> +    "mode": "scoped"
Must be configurable compliant with general approach via the .inc file.

2022-09-08 07:44 UTC, e-grigorov requested changes
I cannot validate the recipe because of: eclipse-kanto/file-backup#17
As a result, I am not sure whether we need to change something.

2022-09-08 13:32 UTC, konstantina-gramatova commented
@hristobojilov The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-09-08 13:43 UTC, e-grigorov commented
> I cannot validate the recipe because of: [eclipse-kanto/file-backup#17](https://github.com/eclipse-kanto/file-backup/issues/17) As a result, I am not sure whether we need to change something.

The backup issue has been resolved. The backup will start now but will log a message that the folder doesn't exist. In the Yocto recipe, could you please ensure that the folder exists i.e. the recipe should create it?

2022-09-08 14:28 UTC, hristobojilov commented
> @hristobojilov The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances 😊
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

2022-09-08 20:51 UTC, e-grigorov requested changes

2022-09-08 20:51 UTC, e-grigorov commented on recipes-management/file-backup/file-backup.inc
> +# The access mode for the the directory to be backed up or restored. Allowed values are: strict,scoped and lax.
- The access mode for the the directory -> The access mode for the directory
- strict,scoped -> strict, scoped

2022-09-08 20:51 UTC, e-grigorov commented on recipes-management/file-backup/file-backup_git.bb
> +LIC_FILES_CHKSUM = "file://src/${GO_IMPORT}/LICENSE;md5=c7cc8aa73fb5717f8291fcec5ce9ed6c"
The project license has been changed and the checksum was updated to: b62cb083c6991f5a8b6f13bf6358094d

2022-09-09 12:19 UTC, e-grigorov approved these changes

2022-09-09 12:27 UTC, konstantina-gramatova approved these changes

2022-09-09 12:38 UTC, merged