Update recipe for Kanto Update Manager
eclipse-kanto/meta-kanto pull request #68
Opened 2023-08-30 07:51 UTC by hristobojilov

[#67] Update recipe for Kanto Update Manager

2023-08-30 12:50 UTC, dimitar-dimitrow requested changes
In [config.json](https://github.com/eclipse-kanto/meta-kanto/blob/main/recipes-management/update-manager/files/config.json) could you set the log directory to 
```@UM_LOG_DD@/kanto-update-manager/kanto-update-manager.log```
Also remove the containers agent name
```
    "agents": {
        "containers": {
            "rebootRequired": false,
            "readTimeout": "30s"
        }
    }
```

2023-08-30 12:50 UTC, dimitar-dimitrow commented on recipes-management/update-manager/files/service.template
> +ExecStart=@UM_BIN_DD@/kanto-update-manager -config-file @UM_CFG_DD@/update-manager/config.json
```suggestion
ExecStart=@UM_BIN_DD@/kanto-update-manager -config-file @UM_CFG_DD@/kanto-update-manager/config.json
```

2023-08-30 13:49 UTC, hristobojilov commented on recipes-management/update-manager/files/service.template
> +ExecStart=@UM_BIN_DD@/kanto-update-manager -config-file @UM_CFG_DD@/update-manager/config.json
the folder name should not not be updated with the executable

2023-08-31 07:34 UTC, dimitar-dimitrow approved these changes

2023-08-31 11:37 UTC, k-gostev approved these changes

2023-08-31 11:38 UTC, merged